<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DirectiveAthena.Website</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DirectiveAthena.Website.Services\DirectiveAthena.Website.Services.csproj" />
    <ProjectReference Include="..\DirectiveAthena.Website.Shared\DirectiveAthena.Website.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Shared.nl.resx">
      <DependentUpon>Shared.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Tags.nl.resx">
      <DependentUpon>Tags.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
