<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>DirectiveAthenaWeb</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions"/>
        <PackageReference Include="JetBrains.Annotations"/>
    </ItemGroup>

</Project>
