<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="InfiniLore.InfiniBlazor" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="MudBlazor" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.BrowserConsole" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Shared.nl.resx">
        <DependentUpon>Shared.cs</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Tags.nl.resx">
        <DependentUpon>Tags.cs</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DirectiveAthena.Website.Services\DirectiveAthena.Website.Services.csproj" />
      <ProjectReference Include="..\DirectiveAthena.Website.Shared\DirectiveAthena.Website.Shared.csproj" />
    </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
      <Content Update="wwwroot\appsettings.local.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' != 'Debug'">
      <Content Remove="wwwroot\appsettings.local.json" />
  </ItemGroup>

  <Target Name="BuildWebpackRelease" BeforeTargets="Publish" Condition="'$(Configuration)' == 'Release'">
    <Message Text="Building webpack bundle (Release)..." Importance="high" />
    <Exec Command="npm run build" WorkingDirectory="$(SolutionDir)src\DirectiveAthena.Website.ClientAssets" />
  </Target>
</Project>
