<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
        <PackageReference Include="MudBlazor"/>
        <PackageReference Include="CodeOfChaos.Extensions"/>
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection"/>
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DirectiveAthenaWeb.Shared\DirectiveAthenaWeb.Shared.csproj" />
      <ProjectReference Include="..\DirectiveAthenaWeb.Components\DirectiveAthenaWeb.Components.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Editor.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Editor.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Tags.nl.resx">
        <DependentUpon>Tags.cs</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

</Project>
