name: Pull Request Tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore DirectiveAthena.Website.slnx

      - name: Run tests
        run: dotnet test DirectiveAthena.Website.slnx --configuration Release --no-restore
