<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    </PropertyGroup>

    <PropertyGroup>
        <ClientAssetsDir Condition="'$(SolutionDir)' != ''">$(SolutionDir)src\DirectiveAthenaWeb.Services.Js</ClientAssetsDir>
        <ClientAssetsDir Condition="'$(ClientAssetsDir)' == ''">$(MSBuildProjectDirectory)\..\DirectiveAthenaWeb.Services.Js</ClientAssetsDir>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="InfiniLore.InfiniBlazor"/>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"/>
        <PackageReference Include="MudBlazor"/>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Extensions.Logging"/>
        <PackageReference Include="Serilog.Sinks.BrowserConsole"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DirectiveAthenaWeb.Components\DirectiveAthenaWeb.Components.csproj"/>
        <ProjectReference Include="..\DirectiveAthenaWeb.Content.Faq\DirectiveAthenaWeb.Content.Faq.csproj" />
        <ProjectReference Include="..\DirectiveAthenaWeb.Content.Note\DirectiveAthenaWeb.Content.Note.csproj" />
        <ProjectReference Include="..\DirectiveAthenaWeb.Content.Story\DirectiveAthenaWeb.Content.Story.csproj" />
        <ProjectReference Include="..\DirectiveAthenaWeb.Services.Contact\DirectiveAthenaWeb.Services.Contact.csproj" />
        <ProjectReference Include="..\DirectiveAthenaWeb.Services.R2Storage\DirectiveAthenaWeb.Services.R2Storage.csproj" />
        <ProjectReference Include="..\DirectiveAthenaWeb.Services.Js\DirectiveAthenaWeb.Services.Js.csproj"/>
        <ProjectReference Include="..\DirectiveAthenaWeb.Services\DirectiveAthenaWeb.Services.csproj"/>
        <ProjectReference Include="..\DirectiveAthenaWeb.Shared\DirectiveAthenaWeb.Shared.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' != 'Debug'">
        <Content Remove="wwwroot\appsettings.local.json"/>
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Update="Resources\Client.nl.resx">
        <DependentUpon>Client.cs</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

    <Target Name="BuildWebpackRelease" BeforeTargets="Publish" Condition="'$(Configuration)' == 'Release'">
        <Message Text="Building webpack bundle (Release)..." Importance="high"/>
        <Exec Command="npm run build" WorkingDirectory="$(ClientAssetsDir)"/>
    </Target>
</Project>
